Method to create or update an interface.
kytos-ng/kytos pull request #118
Opened 2021-06-30 13:13 UTC by ajoaoff

Fixes # 117

Description of the change
----------------------------

New method on switch to create or update an interface.
The whole method executes with a lock acquired, avoiding
racing condition.
New tests for this functionallity implemented.

2021-07-10 09:53 UTC, italovalcy requested changes
@ajoaoff pylint is complaining about some changes that needs to be done. Can you please check that?

2021-07-15 12:17 UTC, italovalcy approved these changes

2021-07-15 12:32 UTC, italovalcy approved these changes

2021-07-15 14:33 UTC, ArturoQuintana approved these changes

2021-08-04 13:30 UTC, merged