Fix/issue 140, unauthenticated git://github.com/ when installing dependencies
kytos-ng/kytos pull request #142
Opened 2021-11-02 19:03 UTC by viniarck

Fixes #140 

### Description of the change

- It turns out unauthenticated URLs starting with git:// is no longer supported by GitHub, so I had to update the requirements file accordingly to a supported format. I hit this when I started to work on a environment from scratch.
- I also disabled the doc tests because of issue #141
- I've also bumped `click` to unblock `black` as a development dependency (since it was conflicting if any NApps were try to install it since `kytos` had a hard dependency on this `click==7.1.1` version). I noticed we still have several frozen deps from 2020, eventually, it might be worth doing a second pass trying to upgrade some of them, reviewing change logs to add important upstream fixes.

2021-11-03 21:05 UTC, italovalcy requested changes
The PR is very good, thanks @viniarck. I've just suggested two changes on the Kytos Sphinx Theme (which was not forked yet, and I just forked to kytos-ng)

2021-11-03 21:05 UTC, italovalcy commented on requirements/dev.in
> +-e git+https://github.com/kytos/sphinx-theme.git#egg=kytos-sphinx-theme
```suggestion
-e git+https://github.com/kytos-ng/sphinx-theme.git#egg=kytos-sphinx-theme
```
I've just forked from the kytos project to kytos-ng

2021-11-03 21:05 UTC, italovalcy commented on requirements/dev.txt
> +-e git+https://github.com/kytos/sphinx-theme.git#egg=kytos-sphinx-theme  # via -r requirements/dev.in
```suggestion
-e git+https://github.com/kytos-ng/sphinx-theme.git#egg=kytos-sphinx-theme  # via -r requirements/dev.in
```

2021-11-04 13:32 UTC, viniarck commented
> The PR is very good, thanks @viniarck. I've just suggested two changes on the Kytos Sphinx Theme (which was not forked yet, and I just forked to kytos-ng)

Awesome. @italovalcy thanks for catching this, and forking the repo. I've just committed the pushed the suggested changes.

2021-11-04 17:40 UTC, italovalcy approved these changes

2021-11-05 11:53 UTC, merged